### ISSUE TITLE
README

### ISSUE THREAD

**Issue by benkeser** [benkeser/survtmle#7]
Add some examples to the README

**Comment by nhejazi** [comment]
random thoughts on this:
* copy some examples from package vignette
* should include calls to the most-used user-facing functions
* move from `README.md` to `README.Rmd` to ensure example reproducibility

**Comment by nhejazi** [comment]
we can now add examples to `README.Rmd` if so desired.

for developers: it's important to run `devtools::use_readme_rmd()` after freshly cloning the package, or if you have not done so before

also, the conversion from `README.Rmd` to `README.md` should be easy to do with the `make md` recipe in `Makefile`.

**Comment by nhejazi** [comment]
@benkeser -- maybe change example so that `timepoints` does not throw warnings?

**Comment by benkeser** [comment]
Should be fixed in 888c5798857ae703fcb407dbe7bdd825d94a147b

**Comment by nhejazi** [comment]
I'm still getting the warnings from re-building the example after re-installing post- 888c579. Would you mind trying `Rscript -e "devtools::install_github('benkeser/survtmle')"`, followed by `make md` at the command line? This should reproduce what I'm seeing (with warnings).

**Comment by benkeser** [comment]
Fixed and README updated in 113457663078f994549edd5417a90a97399df8ca
